version: '3.8'
services:
  kost:
    image: ghcr.io/budi1200/learner-corpus:prod
    container_name: kost
    restart: always
    volumes:
      - ./import:/app/import
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/learner-corpus
    ports:
      - "3030:3000"
    depends_on:
      - postgres
    networks:
      - kost-network
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learner-corpus
    volumes:
      - postgres-kost:/var/lib/postgresql/data
    networks:
      - kost-network
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rokurbanc/.docker/config.json:/config.json
    command: --interval 60 --cleanup
volumes:
  postgres-kost:
    driver: local
networks:
    kost-network:
